### PR TITLE
fixed sqlite initialize fix

### PR DESCRIPTION
**Pull request by stealthAngel**

### CODE REVIEW

**Comment by jepiqueau** [comment]
@stealthAngel i do not really understand what you do seems that you have remove the use of jeep-sqlite

**Comment by stealthAngel** [comment]
In main.ts you have added the jeep SQL. It's already available in the dom

**Comment by stealthAngel** [comment]
In main.ts you have added the jeep SQL. It's already available in the dom.

I also moved the code to an `initializesqliteservice`, 

If you have a create database in the initialization. And you have a query in a page `ngOnInit `(let's say create and get products), the `ngOnInit `gets executed before or during the initialization process ( that creates the table)

The product table isn't available since the initialization is still executing. but we are still trying to create and get products inside it.

This means that you get an error saying the table does not exist.

If we move the initialization to service, we can wait for the initialization to finish before executing ngOnInit.

https://www.learn-angular.fr/how-to-call-an-asynchronous-service-before-bootstrap/

**Comment by jepiqueau** [comment]
@stealthAngel thanks for all your explanations. I didn't have a look in detail and i am not really focusing my time on this. May be you should explain a bit of what you have done in the readme and also change the version number in the package.json as the main change. I will merge all these PR'S later

**Pull request merged**
