### PR TITLE
Products test sample

### PR DESCRIPTION
**Pull request by stealthAngel**
If you have time to look at these improvements:

Created Product page with crud operations.
Created an example repository (Products Repository)
Created a separate class called MigrationService for managing the table creations.
fixed all the tests.spec files into working versions.
updated npm packages
added ionic lab for web testing on two phones at the same time
added database parameter to the environment.ts.
Updated deprecated methods like in spec.ts async to waitforasync.

image

image

image

image

image

image

### CODE REVIEW

**Comment by jepiqueau** [comment]
@stealthAngel can you tell me what you are trying to do ? you are completely changing the app. Will it be useful for others developers as an app starter. I need more explanations before accepting the merges

**Comment by stealthAngel** [comment]
Of course it's usefull, crud functionality has been added. I don't know what other apps would not use crud functionality.

**Comment by stealthAngel** [comment]
I was creating a crud functionality example but I was running against some problems, like the refresh problem that was where it started.

After that I wanted to move the create table script in` app.component.ts `

```
   let query = `
          CREATE TABLE IF NOT EXISTS test (
            id INTEGER PRIMARY KEY NOT NULL,
            name TEXT NOT NULL
          );
```

to another class, but unfortunately, this did not work.


Then I created a crud functionality to give a real-world example of how one could use SQLite database with ionic.
The tests on the main page are excellent, but I believe people also want to see a working example.

Then in the methods, I had to open and close every single method which is against the don't repeat yourself principle.
Sometimes you have to repeat yourself but in this case, particularly it was kinda annoying. So I created two product repositories.
One for quering the normal way with open and close. The other way is with a callback method that handles the open and closes automatically for you.

When I ran `ng test` command, the tests did not work so I thought I'd fix that too when I'm at it.
I removed deprecated methods, and added a global `testbed.config` file so we don't have to do the same dependency injection on every single spec file.


Another problem I faced was there was no option to build the app to production mode.
I added this to the package.json, one can now do `npm run build-production`.
And I edited the readme.


So what actually did change then:

```
    DatabaseService, //a helper method for handling the open and close tag for you see repository for examples
    InitializeSqliteService,   // moved the initialize to it's own service
    {
      provide: APP_INITIALIZER,
      useFactory: initializeFactory,
      deps: [InitializeSqliteService],
      multi: true
    },
    MigrationService, // where the tables are created e.g. if table not exist do this
    ProductRepository, // using databaseservice to query to the database
    ProductDefaultQueryRepository, //the default way of quering to the database
```

Product example routing has been added

All the ng tests have been fixed.

Environment variables 

production build can now be done.

I'd say check the branch out and see the magic.

**Comment by jepiqueau** [comment]
@stealthAngel i will have a look when i got time. I like people adding stuff which help others to develop.as i am not concentrate on software development right now i am refurbishing completely a house  to leave in so that is taking a lot of my time. As i saw quickly a lot of changes coming i was just wondering what you were doing. After having had a look i will certainly merge it no worry

**Comment by stealthAngel** [comment]
Thank you jepiqueau, just take all the time you need.

I hope you'll make something beautiful with your house.

**Comment by jepiqueau** [comment]
@stealthAngel  i would like to merge this but i cannot as there are some conflicts to resolve and i do not know how to do this can you explain me how to proceed

**Comment by stealthAngel** [comment]
Good job I was ready to help

**Pull request merged**
